### ISSUE TITLE
请问下具体配置，在实践代码过程中出现了Segmentation fault (core dumped)问题

### ISSUE THREAD

**Issue by Adora2401** [liucongg/GPT2-NewsTitle#1]
您好，想请问下您的具体配置，主要是版本问题，谢谢。
我的情况是，已经按照您给出的requirements进行了预装，其他环境如下：
Python 3.7.6, CUDA 10.0,Tensorflow-gpu 2.0.0, Keras 2.3.1, Pytorch 1.3.1, cudNN 7.6
NVIDIA GeForce RTX 2080 Ti （矩池云）
在进行train.py时出现了Segmentation fault (core dumped)报错，无log文件也无具体报错信息。查询之后发现与TensorFlow等包的版本有关，想麻烦您share下更具体的信息，谢谢！

**Comment by liucongg** [comment]
> 您好，想请问下您的具体配置，主要是版本问题，谢谢。
> 我的情况是，已经按照您给出的requirements进行了预装，其他环境如下：
> Python 3.7.6, CUDA 10.0,Tensorflow-gpu 2.0.0, Keras 2.3.1, Pytorch 1.3.1, cudNN 7.6
> NVIDIA GeForce RTX 2080 Ti （矩池云）
> 在进行train.py时出现了Segmentation fault (core dumped)报错，无log文件也无具体报错信息。查询之后发现与TensorFlow等包的版本有关，想麻烦您share下更具体的信息，谢谢！

> 您好，想请问下您的具体配置，主要是版本问题，谢谢。
> 我的情况是，已经按照您给出的requirements进行了预装，其他环境如下：
> Python 3.7.6, CUDA 10.0,Tensorflow-gpu 2.0.0, Keras 2.3.1, Pytorch 1.3.1, cudNN 7.6
> NVIDIA GeForce RTX 2080 Ti （矩池云）
> 在进行train.py时出现了Segmentation fault (core dumped)报错，无log文件也无具体报错信息。查询之后发现与TensorFlow等包的版本有关，想麻烦您share下更具体的信息，谢谢！

> 您好，想请问下您的具体配置，主要是版本问题，谢谢。
> 我的情况是，已经按照您给出的requirements进行了预装，其他环境如下：
> Python 3.7.6, CUDA 10.0,Tensorflow-gpu 2.0.0, Keras 2.3.1, Pytorch 1.3.1, cudNN 7.6
> NVIDIA GeForce RTX 2080 Ti （矩池云）
> 在进行train.py时出现了Segmentation fault (core dumped)报错，无log文件也无具体报错信息。查询之后发现与TensorFlow等包的版本有关，想麻烦您share下更具体的信息，谢谢！

应该是你的pytorch版本过低，我得requirements.txt提到了，pytorch >= 1.4。
我这边tensorflow-gpu是1.14版本的。

**Comment by liucongg** [comment]
> 您好，想请问下您的具体配置，主要是版本问题，谢谢。
> 我的情况是，已经按照您给出的requirements进行了预装，其他环境如下：
> Python 3.7.6, CUDA 10.0,Tensorflow-gpu 2.0.0, Keras 2.3.1, Pytorch 1.3.1, cudNN 7.6
> NVIDIA GeForce RTX 2080 Ti （矩池云）
> 在进行train.py时出现了Segmentation fault (core dumped)报错，无log文件也无具体报错信息。查询之后发现与TensorFlow等包的版本有关，想麻烦您share下更具体的信息，谢谢！

应该是你的Pytorch版本过低导致的，我的requirements.txt提到了Pytorch需要>=1.4。
另外，我的tenserflow版本是1.14的，但是我不认为是它所导致的。

**Comment by liucongg** [comment]
> 我的requirements.txt提到了Pytorch需要>=1.4。
> 另外，我的tenserflow版本是1.14的，但是我不认为是它所导致的。

补充一下：我这边自己的配置，Python3.6，CUDA 10.0,Tensorflow-gpu 1.14, Pytorch 1.4, cudNN 7.6

**Comment by Adora2401** [comment]
非常感谢，排查出是提供方的GPU配置有问题，已经解决。
