### ISSUE TITLE
请问定义数据类的时候为什么要减3呢？

### ISSUE THREAD

**Issue by jdcmj** [liucongg/GPT2-NewsTitle#11]
请问，在data_set.py文件中，第90行，if len(content_tokens) > self.max_len - len(title_tokens) - 3，请问这里为什么间3呢，是减去[CLS]和[SEP]标志符吗？那不是应该减2吗？

**Comment by liucongg** [comment]
一个【cls】，两个【sep】。【cls】content【sep】title【sep】
