### ISSUE TITLE
分享几个有趣的结果，这个用来搞笑是挺不错的！

### ISSUE THREAD

**Issue by KuangDD** [liucongg/GPT2-NewsTitle#12]
输入的新闻正文为:参差感，或者说多元化，是今年《创造营2021》带来的一个大惊喜。学员的选角和发起人团的构成中，除了国际化这一特点外，学员们还有街舞、电竞、上班族等不同背景，发起人团成员来自影视、音乐、团体等不同领域——通过十期节目，《创造营2021》真实且深刻地呈现了不同成长背景下，多元文化、多元价值观碰撞与交流的过程。
生成的第1个标题为：“创造营2025”
生成的第2个标题为：《创造营space]营螂》真实于是什么样的？
生成的第3个标题为：学者：国际化的选角和发起人团体

神评论：GPT2新技能：预测未来！坐等创造营2025

输入的新闻正文为:从刘宇身上，能感受到的是十余年中国舞学习经历中所习得的文雅；赞多和力丸两位来自日本的世界级街舞舞者，展现出强悍的舞蹈实力，但同时二人身上又始终透露着来到异国他乡的彷徨失措；从夏威夷追梦到日本、再来到中国的米卡，则处处透露出对音乐的热爱，对友情的真诚。
生成的第1个标题为：中国舞蹈者：用力模仿奇幻
生成的第2个标题为：大写给力量
生成的第3个标题为：刘宇之父：中国的米卡

神评论：中国的米卡成为了刘宇的父亲，米卡改国籍还可以收获一个儿子！

**Comment by KuangDD** [comment]
中国舞蹈者：用力模仿奇幻

这个标题是挺神的，不得不说，GPT2还有激发灵感的功能！

**Comment by liucongg** [comment]
> 中国舞蹈者：用力模仿奇幻
> 
> 这个标题是挺神的，不得不说，GPT2还有激发灵感的功能！

**Comment by cedar33** [comment]
所以。。。这个能应用在生产环境？
