### ISSUE TITLE
关于使用预训练GPT2权重的问题

### ISSUE THREAD

**Issue by Kaicheng-Yang0828** [liucongg/GPT2-NewsTitle#16]
Hi,我使用预训练的GPT2模型（https://github.com/Morizeyao/GPT2-Chinese）并在微博数据上进行了实验，test_loss和train_loss都得到了大幅提升，如下图所示：
![1636534305(1)](https://user-images.githubusercontent.com/39723624/141080952-61e82b97-a21b-400b-8002-536b67c8e341.png)
![1636534317(1)](https://user-images.githubusercontent.com/39723624/141080981-fe27b5da-75dd-44c0-8a8e-c80ab15f74ca.png)
但是我是用测试集上的数据进行测试，却发现标题生成的效果似乎变差了，
![1636534391(1)](https://user-images.githubusercontent.com/39723624/141081205-7c9598cf-9036-4cc1-9f53-28515c3fe015.png)
![1636534416(1)](https://user-images.githubusercontent.com/39723624/141081267-60c41b79-c08d-431c-8f34-c5028a80dbfc.png)
不知道您对这个结果有什么看法？

**Comment by liucongg** [comment]
> Hi,我使用预训练的GPT2模型（[https://github.com/Morizeyao/GPT2-Chinese）并在微博数据上进行了实验，test_loss和train_loss都得到了大幅提升，如下图所示：](https://github.com/Morizeyao/GPT2-Chinese%EF%BC%89%E5%B9%B6%E5%9C%A8%E5%BE%AE%E5%8D%9A%E6%95%B0%E6%8D%AE%E4%B8%8A%E8%BF%9B%E8%A1%8C%E4%BA%86%E5%AE%9E%E9%AA%8C%EF%BC%8Ctest_loss%E5%92%8Ctrain_loss%E9%83%BD%E5%BE%97%E5%88%B0%E4%BA%86%E5%A4%A7%E5%B9%85%E6%8F%90%E5%8D%87%EF%BC%8C%E5%A6%82%E4%B8%8B%E5%9B%BE%E6%89%80%E7%A4%BA%EF%BC%9A) ![1636534305(1)](https://user-images.githubusercontent.com/39723624/141080952-61e82b97-a21b-400b-8002-536b67c8e341.png) ![1636534317(1)](https://user-images.githubusercontent.com/39723624/141080981-fe27b5da-75dd-44c0-8a8e-c80ab15f74ca.png) 但是我是用测试集上的数据进行测试，却发现标题生成的效果似乎变差了， ![1636534391(1)](https://user-images.githubusercontent.com/39723624/141081205-7c9598cf-9036-4cc1-9f53-28515c3fe015.png) ![1636534416(1)](https://user-images.githubusercontent.com/39723624/141081267-60c41b79-c08d-431c-8f34-c5028a80dbfc.png) 不知道您对这个结果有什么看法？

我不知道你又没有用我得代码，我代码中将文本和标题进行了区分，并且loss我只计算了生成部分的。
