### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by pureblacker** [liucongg/GPT2-NewsTitle#18]
为什么不用预训练模型的参数呢？用预训练模型的意义不就在此吗？小白不是很懂，，，，

**Comment by liucongg** [comment]
> 为什么不用预训练模型的参数呢？用预训练模型的意义不就在此吗？小白不是很懂，，，，
当时没有开源并且针对大量数据训练的GPT2模型

**Comment by pureblacker** [comment]
哦哦这样啊，谢谢
如果不打扰的话，还想问您几个问题，为什么分词器都使用bert的分词器而不是jieba呢，中文分词为什么都是单个字而不是有意义的词语呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liucongg/GPT2-NewsTitle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liucongg/GPT2-NewsTitle] 预训练模型 (Issue #18)





  
为什么不用预训练模型的参数呢？用预训练模型的意义不就在此吗？小白不是很懂，，，，
 当时没有开源并且针对大量数据训练的GPT2模型
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
