### ISSUE TITLE
forward() got an unexpected keyword argument 'past'

### ISSUE THREAD

**Issue by zhx7723** [liucongg/GPT2-NewsTitle#34]
![image](https://user-images.githubusercontent.com/73454784/175776761-bd03d354-ea3b-45aa-9076-9fd4c99977c3.png)

**Comment by zhx7723** [comment]
![image](https://user-images.githubusercontent.com/73454784/175776907-b30d8470-21eb-4de7-98aa-653f41a7569b.png)
我好像解决了

**Comment by ta-xiang** [comment]
确实 牛的
