### ISSUE TITLE
是不是会出现 len(title_tokens) > self.max_len 的情况，这样会引起下面的 assert错误？

### ISSUE THREAD

**Issue by 1024er** [liucongg/GPT2-NewsTitle#4]
def convert_feature(self, sample):
       ...
        input_ids = []
        token_type_ids = []
        # 对新闻正文进行tokenizer.tokenize分词
        content_tokens = self.tokenizer.tokenize(sample["content"])
        # 对新闻标题进行tokenizer.tokenize分词，注意tokenizer中已经将[Space]作为一个分隔符，不会切割成多个字符
        title_tokens = self.tokenizer.tokenize(sample["title"].replace(" ", "[Space]"))
        # 判断如果正文过长，进行截断
        if len(content_tokens) > self.max_len - len(title_tokens) - 3:
            content_tokens = content_tokens[:self.max_len - len(title_tokens) - 3]
...

---------
是不是会出现 len(title_tokens) > self.max_len 的情况，这样会引起下面的 assert错误？

**Comment by liucongg** [comment]
bug小能手。
确实会出现这个问题，我这里默认title（一般较短）会比max短。后期代码我会做更新，增加max_title_len配置项
