### ISSUE TITLE
出现报错，不知道怎么解决，万分感谢！是缺少对应文件吗？

### ISSUE THREAD

**Issue by tt0408** [liucongg/GPT2-NewsTitle#40]
OSError: model/gpt_code_v1 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by RealizationAndGrowth** [comment]
模型文件没有下载，把模型文件下载下来，放到对应目录就好了
