### ISSUE TITLE
为什么train文件训练出的pytorch模型，处理新闻后会出现乱码

### ISSUE THREAD

**Issue by 845317039** [liucongg/GPT2-NewsTitle#41]
请问作者，我用的项目给的处理后的数据集，在train文件里训练后，生成了checkpoint-0文件夹，我把这个模型放到generate.title文件里后，可以正常运行，但是处理输入的新闻后会出现乱码结果，不知道是哪里的情况，编码也是utf8正确的
![image](https://user-images.githubusercontent.com/129351798/228715420-8dca2281-b309-493f-85ad-c03b3ae58786.png)

**Comment by 845317039** [comment]
另外那要处理自己数据集的话，该是什么格式呢，和train-data一样的格式可以吗

**Comment by liucongg** [comment]
需要数据格式一致

**Comment by 845317039** [comment]
谢谢回复，上周末解决了这个问题，是因为之前测试读取数据是否正常的时候生成的cached_train和cached_test缓存文件没有清除，改掉后就正常了
我想基于这个模型做一个对中文新闻的实例抽取和事件抽取模型，正在用gpt2medium预训练模型做训练，目前loss率还是比较高，预测效果还是不太好，我正在继续调整












wwdz
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 下午3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liucongg/GPT2-NewsTitle] 为什么train文件训练出的pytorch模型，处理新闻后会出现乱码 (Issue #41)




 
需要数据格式一致
