### ISSUE TITLE
请问下，如果出现len(input_ids) <= self.max_len,要怎么处理呢？

### ISSUE THREAD

**Issue by dtMndas** [liucongg/GPT2-NewsTitle#5]
针对新闻数据集，在data_set.py中，设置self.max_len = 1024。容易出现input_ids 的长度大于self.max_len，要怎么处理呢
大致统计了下微信新闻数据集的长度，最长是3w+，最短是27，中位数在1000左右，要怎么设置max_len才好呢

**Comment by liucongg** [comment]
在data_set.py文件中，第90行，
if len(content_tokens) > self.max_len - len(title_tokens) - 3:
    content_tokens = content_tokens[:self.max_len - len(title_tokens) - 3]
会对正文进行处理，因此不应该出现input_ids 的长度大于self.max_len。
除非是len(title_tokens)大于 self.max_len-3，但是理论上是不会的。

**Comment by liucongg** [comment]
> 针对新闻数据集，在data_set.py中，设置self.max_len = 1024。容易出现input_ids 的长度大于self.max_len，要怎么处理呢
> 大致统计了下微信新闻数据集的长度，最长是3w+，最短是27，中位数在1000左右，要怎么设置max_len才好呢

在data_set.py文件中，第90行，
if len(content_tokens) > self.max_len - len(title_tokens) - 3:
    content_tokens = content_tokens[:self.max_len - len(title_tokens) - 3]
会对正文进行处理，因此不应该出现input_ids 的长度大于self.max_len。
除非是len(title_tokens)大于 self.max_len-3，但是理论上是不会的。
