### ISSUE TITLE
“清洗htlm标记”写错了

### ISSUE THREAD

**Issue by nlpofwhat** [liucongg/GPT2-NewsTitle#6]
大佬，清洗htlm标记写错了？

**Comment by liucongg** [comment]
> 大佬，清洗htlm标记写错了？

具体哪一行呢，感谢指出

**Comment by nlpofwhat** [comment]
UpDate 01.02.2021栏第3行

**Comment by liucongg** [comment]
> UpDate 01.02.2021栏第3行

好的，原来是readme，还以为代码错了，下次更新时候，做修改，感谢提醒。
