### ISSUE TITLE
想问问这是不是严格意义的GPT模型，个人感觉更像是类似于UniLM的Seq2Seq

### ISSUE THREAD

**Issue by anwjedb** [liucongg/GPT2-NewsTitle#7]
感谢您的工作，因为初学所以对一些概念会比较抠字眼想搞明白，大佬见谅哈哈。您在模型优化时只计算了标题的loss，那么优化的就是P(标题|正文)，一种条件概率，感觉这是一种seq2seq呀（有条件的语言模型），transformer同时作为了编码器和解码器，就和UniLM一样的思想，只是正文和标题您这里都用的GPT的单向注意力，而UniLM正文用双向，标题用单向。如果是严格意义的GPT，我的理解是无条件的语言模型，建模的是P(Y)，而不是P(Y|X)，会完整地“自己预测自己”，比如将正文标题拼接后作为一个完整的文本，然后错开一位，完整自己预测自己，当然这样的实现没有显式区分二者边界也不太适合实现标题生成，不知我的理解是否有误，谢谢大佬

**Comment by liucongg** [comment]
1、GPT2模型本身就只有transforme的解码器部分。
2、在模型训练时只计算了标题的loss，你可以理解为在进行fine-tuning，训练一个文档生成标题的下游任务，而不是原始的语言模型任务。
3、unilm和gpt2进行生成的本质区别是，unilm在内容编码部分是双向的，标题生成部分相当于预测被掩掉的[mask]，gpt2在内容编码部分是单向的，标题生成部分就是逐字预测。我并不认同你说的gpt2“不太适合实现标题生成”。
从效果上来看，我这边做过unilm和gpt2的对比，差不多。

**Comment by anwjedb** [comment]
> 1、GPT2模型本身就只有transforme的解码器部分。
> 2、在模型训练时只计算了标题的loss，你可以理解为在进行fine-tuning，训练一个文档生成标题的下游任务，而不是原始的语言模型任务。
> 3、unilm和gpt2进行生成的本质区别是，unilm在内容编码部分是双向的，标题生成部分相当于预测被掩掉的[mask]，gpt2在内容编码部分是单向的，标题生成部分就是逐字预测。我并不认同你说的gpt2“不太适合实现标题生成”。
> 从效果上来看，我这边做过unilm和gpt2的对比，差不多。

感谢，我的问题应该是没理清预训练和微调阶段 ，GPT预训练阶段是用语言模型的模式，但不代表微调阶段就不能用seq2seq的方式
